### ISSUE TITLE
add check to not rerun job contained in the cache

### ISSUE THREAD

**Issue by slawler** [Dewberry/process-api#2]
@ar-siddiqui do you think there may be a good use case to not destroy the sync results in case of repeated requests? Also, should we add a check to see (stop) jobs that are identical?

**Comment by ar-siddiqui** [comment]
There is definitely a case for having a regular cache for sync processes that are not dependent on resources, for example, finding max min flood level for a location. If the user, submits multiple such requests within a short time we return the same result. But for the processes dependent on other resources (and we have discussed that they will not be synced) we can't have a cache because the underlying resources (like raster) may have changed, and the user is requesting a new run.

We can check the timestamp on files to see if they have been updated, but that may be overcomplicating things.
